#version 430 core

struct Camera {
    vec3 pos;
    vec3 lookDir;
};

struct Mat {
    int type;
    vec3 color;
    float[2] data;
};

struct Sphere {
    vec3 pos;
    float rad;
    Mat mat;
};

struct Triangle {
    vec3 v0;
    vec3 v1;
    vec3 v2;
};

struct AABB {
    vec3 min;
    vec3 max;
};

struct BVHNode {
    AABB aabb;
    int left;
    int right;
    int triangle;
};

struct Light {
    vec3 pos;
    float rad;
    vec3 color;
    float intensity;
};

struct Plane {
    vec3 origin;
    vec3 normal;
    Mat mat;
};

struct Ray {
    vec3 origin;
    vec3 dir;
    vec3 throughput;
    vec3 radiance;
};

struct Hit {
    float t;
    vec3 normal;
    Mat mat;
    bool inside;
};

layout(std430, binding = 0) buffer TrianglesBuffer {
    Triangle triangles[];
};
uniform int numTriangles;

layout(std430, binding = 1) buffer BVHBuffer {
    BVHNode nodes[];
};
uniform int numBVHNodes;
uniform int debugBVH;
uniform vec3 modelPos;

#define NUM_SPHERE 3
#define NUM_PLANE 1
#define NUM_LIGHT 1

struct World {
    Sphere spheres[NUM_SPHERE];
    Plane planes[NUM_PLANE];
#if NUM_LIGHT > 0
    Light lights[NUM_LIGHT];
#endif
};

struct RaycastData {
    Hit hit;
    Ray ray;
    uint seed;
};

out vec4 FragColor;
layout (location = 1) uniform vec4 metalProperties;
layout (location = 2) uniform vec2 texSize;
layout (location = 3) uniform sampler2D screenTex;
layout (location = 4) uniform int frameCount;
layout (location = 5) uniform int bsdfType;
layout (location = 6) uniform float ballRoughness;
layout (location = 7) uniform int samples;
layout (location = 8) uniform vec2 winSize;
layout (location = 9) uniform int maxBounces;
layout (location = 10) uniform float refractionIndex;
layout (location = 11) uniform bool useModel;
uniform Camera camera;
in vec4 vClipPos;

//#define SAMPLES 1
#define EPS 1e-4
#define PROBA_EPS 1e-6
#define MAX_NONEMIT_BOUNCE 10
#define PI 3.14159265
#define CONSTANT1_FON (0.5 - 2 / (3 * PI))
#define CONSTANT2_FON (2 / 3 - 28 / (15 * PI))

#define MAT_DIFF 0
#define MAT_GLOSSY 1
#define MAT_EMIT 2
#define MAT_GLASS 3
#define MAT_METAL 4

#define updateData(data) data = RaycastData(hit, ray, seed)
#define unwrapData(data) ray = data.ray; hit = data.hit; seed = data.seed

#define mData(d0, d1) float[2](d0, d1)
#define mData0(d) float[2](d, 0)
#define mData1(d) float[2](0, d)
#define mNoData() float[2](0, 0)

#define diffuseRoughness(m) m.data[0]
#define pbrFuzz(m) m.data[0]              
#define pbrMetallic(m) m.data[1]
#define emitIntensity(m) m.data[0]          
#define glassIndex(m) m.data[0]

#define BSDF_LAMBERT 0
#define BSDF_LAMBERT_WRAP 1
#define BSDF_OREN_NAYAR 2

#define LAMBERT 0
#define QON 1
#define FON 2
#define EON 3

// -------------------- UTILS

#pragma include "./rand.glsl"
#pragma include "./utils.glsl"
#pragma include "./intersections.glsl"

#pragma FDECLARE
// RAND.GLSL
uint initSeed(uvec2 pos, uint frame);
float rand(inout uint seed);
vec3 randomInSphere(inout uint seed);
vec3 randomOnUnitSphere(inout uint seed);
vec3 randomOnUnitHemiphere(inout uint seed, vec3 normal);
vec3 randomCosineHemisphere(inout uint seed, vec3 normal, float randomizationFactor);
vec3 randomGGXHemisphere(inout uint seed, vec3 normal, float alpha);

// UTILS.GLSL
vec2 ratio(vec2 vec);
vec3 reflect(vec3 I, vec3 N);
vec3 refract(vec3 I, vec3 N, float n);
void stop(inout Hit hit, bool touchedLight);
float luminanceMean(vec3 c);

// INTERSECTIONS.GLSL
Hit rayIntersection(World world, inout Ray ray);
#pragma FEND

// -------------------- LIGHTS

// brdfs

vec3 lambert(Hit hit){
    return hit.mat.color / PI;
}

float cosPhiDiff(vec3 normal, vec3 lightDir, vec3 viewDir){
    vec3 Lp = normalize(lightDir - normal * dot(lightDir, normal));
    vec3 Vp = normalize(viewDir - normal * dot(viewDir, normal));

    return dot(Lp, Vp);
}

float ltc_d(float dotProd, float r){
    return r*(0.540852f + (-1.01625f + 0.475392f*dotProd)*dotProd)/(-1.0743f + (0.0725628f + dotProd)*dotProd);
}

// Energy generated by FON
float E_FON_approx(float dotProd, float r)
{
    float mucomp = 1.0f - dotProd;
    const float g1 = 0.0571085289f;
    const float g2 = 0.491881867f;
    const float g3 = -0.332181442f;
    const float g4 = 0.0714429953f;
    float GoverPi = mucomp * (g1 + mucomp * (g2 + mucomp * (g3 + mucomp * g4)));
    return (1.0f + r * GoverPi) / (1.0f + CONSTANT1_FON * r);
}

vec3 oren_nayar(Hit hit, vec3 normal, vec3 lightDir, vec3 viewDir, float roughness){
    vec3 lambert = lambert(hit);
    if (bsdfType == LAMBERT || roughness < EPS) return lambert;

    float NdotL = max(dot(normal, lightDir), 0);
    float NdotV = max(dot(normal, viewDir), 0);

    if (bsdfType == QON){
        float sigma2 = pow(roughness * PI * 0.5, 2);
        float A = 1 - 0.5 * sigma2 / (sigma2 + 0.33);
        float B = 0.45 * sigma2 / (sigma2 + 0.09);

        float cosPhi = max(0, cosPhiDiff(normal, lightDir, viewDir));
        float s2 = cosPhi * cosPhi * (1 - NdotL * NdotL) * (1 - NdotV * NdotV);
        float oneOverTq = cosPhi <= 0 ? 0 : 1 / max(NdotL, NdotV);
        float angleTerm = A + B * sqrt(s2) * oneOverTq;
        return angleTerm * lambert;
    }
    else {
        float A = 1 / (1 + CONSTANT1_FON * roughness);
        float B = roughness * A;

        float cosPhi = max(0, cosPhiDiff(normal, lightDir, viewDir));
        float s2 = cosPhi * cosPhi * (1 - NdotL * NdotL) * (1 - NdotV * NdotV);
        float tq = cosPhi <= 0 ? 1 : max(NdotL, NdotV);
        vec3 angleTerm = vec3(A + B * sqrt(s2) / tq);

        if (bsdfType == EON){
            float EL = E_FON_approx(NdotL, roughness);
            float EV = E_FON_approx(NdotV, roughness);
            float avgE = A * (1 + CONSTANT2_FON * roughness);
            vec3 F = hit.mat.color * avgE / (vec3(1) - hit.mat.color * (1 - avgE));
            angleTerm += F * max(1 - EL, EPS) * max(1 - EV, EPS) / max(1 - avgE, EPS);
        }
        return lambert * angleTerm;
    }

    return lambert;
}

vec3 schlickFresnel(float VdotH, vec3 F0)
{
    return F0 + (vec3(1) - F0) * pow(1 - VdotH, 5);
}

float DGTR(float a2, float NdotH){
    float denom = NdotH * NdotH * (a2 - 1) + 1;
    return a2 / max(PI * denom * denom, PROBA_EPS);
}

float G1GTR(float a2, float NdotW){
    if (NdotW <= 0.0) return 0.0;

    float NdotW2 = NdotW * NdotW;
    float tan2 = (1.0 - NdotW2) / max(NdotW2, PROBA_EPS);
    return 2.0 / (1.0 + sqrt(1.0 + a2 * tan2));
}

vec3 cookTorrance(Hit hit, vec3 viewDir, vec3 lightDir, float alpha, bool simplify){
    vec3 h = normalize(lightDir + viewDir);
    float NdotL = max(dot(hit.normal, lightDir), 0);
    float NdotV = max(dot(viewDir, hit.normal), 0);
    float VdotH = max(dot(h, viewDir), EPS);
    float a2 = alpha * alpha;
    float D = 1; // D is simplified with the PDF
    if (!simplify){
        float NdotH = max(dot(hit.normal, h), 0);
        D = DGTR(a2, NdotH);
    }
    float G = G1GTR(a2, NdotV) * G1GTR(a2, NdotL);
    vec3 F = schlickFresnel(VdotH, hit.mat.color);

    return F * D * G / max(4 * NdotV * (simplify ? 1 : NdotL), PROBA_EPS);
}

// pdfs

float p_direct(Light light, float distance, float cosLight){
    return distance * distance / (cosLight * 2 * PI * light.rad * light.rad * NUM_LIGHT);
}

float shadow_hit(Light light, World world, Ray ray){
    Hit hit = rayIntersection(world, ray);
    vec3 hitPos = ray.origin + ray.dir * hit.t;
    if (hit.t > 0 && length(hitPos - light.pos) > light.rad + sqrt(EPS)) return 0;
    return 1;
}

float p_cosineHemisphere(vec3 normal, vec3 w){
    return max(0, dot(normal, w)) / PI;
}

float p_GGX(vec3 normal, vec3 l, vec3 v, float alpha, bool simplify){
    vec3 h = normalize(l + v);
    float NdotH = max(dot(normal, h), 0.0);
    float VdotH = max(dot(v, h), 0.0);
    float D = 1;
    if (!simplify) D = DGTR(alpha * alpha, NdotH);
    return D * NdotH / max(4.0 * VdotH, PROBA_EPS);
}

// lighting functions

void russianRoulette(inout RaycastData data){
    Ray ray; Hit hit; uint seed;
    unwrapData(data);
    
    float prob = max(max(ray.throughput.r, ray.throughput.g), ray.throughput.b);
    if (rand(seed) > prob) {
        stop(hit, false);
    }  
    else { ray.throughput /= max(min(prob, 1), EPS); }

    updateData(data);
}

float sampleLight(inout RaycastData data, Light light){
    Ray ray; Hit hit; uint seed;
    unwrapData(data);

    vec3 nLight = randomOnUnitHemiphere(seed, ray.origin - light.pos);
    vec3 lightPoint = light.pos + nLight * light.rad;
    vec3 newDir = normalize(lightPoint - ray.origin);
    ray.dir = newDir;

    float NdotL = max(dot(hit.normal, newDir), 0);
    float LdotNl = max(dot(-newDir, nLight), 0);
    
    float distance = length(lightPoint - ray.origin);
    float pdirect = p_direct(light, distance, LdotNl);
    ray.throughput *= NdotL;

    updateData(data);
    return pdirect;
}

void diffuse(World world, inout RaycastData data){
    Ray ray; Hit hit; uint seed;
    unwrapData(data);
    ray.origin += hit.t * ray.dir + EPS * hit.normal;

    Light light;
#if NUM_LIGHT > 0
    light = world.lights[int(rand(seed) * NUM_LIGHT)];
#endif

    // MIS
    float wdirect = 0.2;
    wdirect = NUM_LIGHT > 0 ? wdirect : 0;
    float wbsdf = 1 - wdirect;
    float r = rand(seed);
    float orenNayarRoughness = diffuseRoughness(hit.mat);
    vec3 viewDir = -ray.dir;

    if (r < wbsdf){
        // BSDF sampling
        vec3 newDir = randomCosineHemisphere(seed, hit.normal, 1);
        vec3 f_r = oren_nayar(hit, hit.normal, newDir, viewDir, orenNayarRoughness);
        ray.throughput *= f_r * PI / wbsdf;
        ray.dir = newDir;

        // Check if we hit a light with the BSDF sampling
        Hit nextHit = rayIntersection(world, ray);
        if (nextHit.t > 0 && nextHit.mat.type == MAT_EMIT){
            vec3 Le = nextHit.mat.color * emitIntensity(nextHit.mat);
            float LdotNl = max(dot(-newDir, nextHit.normal), 1);

            float pdirect = p_direct(light, nextHit.t, LdotNl)
                            * shadow_hit(light, world, ray);
            float pbsdf = p_cosineHemisphere(hit.normal, newDir);
            float weight = wbsdf * pbsdf / (wbsdf * pbsdf + wdirect * pdirect);

            ray.radiance += clamp(ray.throughput * weight, 0, 1.3) * Le;
            stop(hit, true);
        }
    } 
    else {
        // Direct lighting
        updateData(data);
        float pdirect = sampleLight(data, light);
        unwrapData(data);
        vec3 f_r = oren_nayar(hit, hit.normal, ray.dir, viewDir, orenNayarRoughness);
        ray.throughput *= f_r;

        if (shadow_hit(light, world, ray) > 0){
            float pbsdf = p_cosineHemisphere(hit.normal, ray.dir);
            float weight = 1.0 / (wdirect * pdirect + wbsdf * pbsdf);
            vec3 Le = light.intensity * light.color;
            ray.radiance += clamp(ray.throughput * weight, 0, 1.3) * Le;
            stop(hit, true);
        }
        else{
            ray.throughput /= pdirect * wdirect;
            stop(hit, false);
        }
    }

    updateData(data);
    russianRoulette(data);
}

void metal(World world, inout RaycastData data){
    Ray ray; Hit hit; uint seed;
    unwrapData(data);
    Light light;
#if NUM_LIGHT > 0
    light = world.lights[int(rand(seed) * NUM_LIGHT)];
#endif
    ray.origin += hit.t * ray.dir + hit.normal * EPS;
    
    if (pbrFuzz(hit.mat) < EPS){
        vec3 newDir = reflect(ray.dir, hit.normal);
        float VdotN = max(dot(-ray.dir, hit.normal), 0.0);
        vec3 f_r = schlickFresnel(VdotN, hit.mat.color);
        ray.throughput *= f_r;
        ray.dir = newDir;
        data = RaycastData(hit, ray, seed);
        return;
    }

    // MIS
    float fuzz = pbrFuzz(hit.mat);
    float alpha = fuzz * fuzz;
    float wdirect = 0.3 * alpha;
    float wGGX = 1 - wdirect;
    wdirect = NUM_LIGHT > 0 ? wdirect : 0;
    wGGX = NUM_LIGHT > 0 ? wGGX : 1;
    float r = rand(seed);
    if (r < wGGX){
        vec3 viewDir = -ray.dir;
        vec3 h = randomGGXHemisphere(seed, hit.normal, alpha);
        vec3 newDir = mix(reflect(-viewDir, h), hit.normal, 0);
        
        float pGGX = p_GGX(hit.normal, newDir, viewDir, alpha, true);
        vec3 f_r = cookTorrance(hit, viewDir, newDir, alpha, true);
        ray.throughput *= f_r /* * NdotL (but is in cookTorrance) */ / (pGGX * wGGX);
        ray.dir = newDir;

        Hit nextHit = rayIntersection(world, ray);
        if (nextHit.t > 0 && nextHit.mat.type == MAT_EMIT){
            vec3 Le = nextHit.mat.color * emitIntensity(nextHit.mat);
            float LdotNl = max(dot(-newDir, nextHit.normal), 0);
            float pdirect = p_direct(light, nextHit.t, LdotNl)
                            * shadow_hit(light, world, ray);
            float weight = wGGX * pGGX / (wGGX * pGGX + wdirect * pdirect);

            ray.radiance += clamp(ray.throughput * weight, 0, 1.5) * Le;
            stop(hit, true);
        }
    }
    else{
        // Direct lighting
        vec3 viewDir = -ray.dir;
        updateData(data);
        float pdirect = sampleLight(data, light);
        unwrapData(data);
        vec3 f_r = cookTorrance(hit, viewDir, ray.dir, alpha, false);
        ray.throughput *= f_r;

        if (shadow_hit(light, world, ray) > 0){
            float pGGX = p_GGX(hit.normal, ray.dir, viewDir, alpha, false);
            float weight = 1.0 / (wdirect * pdirect + wGGX * pGGX);
            vec3 Le = light.color * light.intensity;
            ray.radiance += clamp(ray.throughput * weight, 0, 1.5) * Le;
            stop(hit, true);
        }
        else{
            ray.throughput /= (wdirect * pdirect);
            stop(hit, false);
        }
    }

    updateData(data);
    russianRoulette(data);
}

void glass(inout RaycastData data){
    Ray ray; Hit hit; uint seed;
    unwrapData(data);

    float n = 1 / glassIndex(hit.mat);
    vec3 normal = hit.normal;
    if (hit.inside){
        n = 1 / n;
        normal *= -1;
    }

    float NdotV = dot(normal, -ray.dir);
    bool totalReflection = n * n * (1 - NdotV * NdotV) > 1;
    float f0 = (1 - n) / (1 + n);
    f0 = f0 * f0;
    float reflectance = schlickFresnel(NdotV, vec3(f0)).x;
    if (totalReflection || rand(seed) < reflectance){
        ray.origin += hit.t * ray.dir + EPS * normal;
        ray.dir = reflect(ray.dir, hit.normal);
    }
    else{
        ray.origin += hit.t * ray.dir - EPS * normal;
        ray.dir = refract(ray.dir, normal, n);
    }

    if (hit.inside){
        vec3 absorption = exp(-(vec3(1) - hit.mat.color) * hit.t); // Beer-Lambert
        ray.throughput *= absorption;
    }
    updateData(data);
}

void glossy(World world, inout RaycastData data){
    Ray ray; Hit hit; uint seed;
    unwrapData(data);

    float metallic = pbrMetallic(hit.mat);
    vec3 F0 = vec3(pow(metallic / (2 - metallic), 2));
    float F = luminanceMean(schlickFresnel(dot(-ray.dir, hit.normal), F0));
    if (rand(seed) < F){
        data.hit.mat.color = vec3(1);
        metal(world, data);
    }
    else{
        data.hit.mat.data = mData(0, data.hit.mat.data[1]);
        diffuse(world, data);
    }
}

void emit(inout RaycastData data){
    data.ray.radiance += data.ray.throughput * data.hit.mat.color * emitIntensity(data.hit.mat);
    data.hit.t = -1;
}

void computeLighting(World world, in out Hit hit, in out Ray ray, in out uint seed){
    if (hit.t < 0) return;

    RaycastData data = RaycastData(hit, ray, seed);
    switch (hit.mat.type){
        case MAT_DIFF:
            diffuse(world, data);
            break;
        case MAT_GLOSSY:
            glossy(world, data);
            break;
        case MAT_METAL:
            metal(world, data);
            break;
        case MAT_GLASS:
            glass(data);
            break;
        case MAT_EMIT:
            emit(data);
            break;
    }
    unwrapData(data);
}

// RAY TRACING --------------------

Ray fovRay(vec2 pos, Ray ray){
    float fov = radians(mix(50, 90, 0 / 8.0));
    vec3 forward = normalize(camera.lookDir);

    vec3 worldUp = abs(forward.y) < 0.999
                 ? vec3(0,1,0)
                 : vec3(0,0,1);

    vec3 right = normalize(cross(forward, worldUp));
    vec3 up    = cross(right, forward);

    float tanHalfFov = tan(fov * 0.5);

    vec3 dir = forward + (right * pos.x + up * pos.y) * tanHalfFov;
    ray.dir = normalize(dir);
    return ray;
}

vec3 sun(vec3 lookingAt)
{
    vec3 sunDir = normalize(vec3(0.2, 0.6, 0.7));
    float sunAngularRadius = radians(4);
    float sunIntensity = 50.0;
    float cosAngle = dot(lookingAt, sunDir);
    float sun = smoothstep(
        cos(sunAngularRadius),
        cos(sunAngularRadius * 0.8),
        cosAngle
    );
    return vec3(sunIntensity) * sun;
}

vec3 horizon(vec3 lookingAt){
    float a = (dot(normalize(lookingAt), vec3(0,1,0)) + 1) * 0.5;
    vec3 top = vec3(0.32, 0.55, 0.78);
    vec3 bot = vec3(0.62, 0.72, 0.85);
    return mix(bot, top, a) * 0.7;
}

vec3 sky(vec3 lookingAt){
    return horizon(lookingAt);
}

vec4 rayColor(World world, in out uint seed, Ray ray){
    Ray tracedRay = ray;
    for (int i = 0; i < maxBounces; i++){

        Hit hit = rayIntersection(world, tracedRay);
        //if (hit.t > 0) tracedRay.throughput *= exp(-hit.t * 0.015);
        computeLighting(world, hit, tracedRay, seed);

        if (hit.t < 0){
            if (hit.t > -2) tracedRay.radiance += tracedRay.throughput * sky(tracedRay.dir);
            return vec4(tracedRay.radiance, 1);
        }// Cas ou on tombe sur une light ou sur rien
    }

    return vec4(0);
}

void main()
{
    float resolutionFactor = winSize.x / texSize.x;
    uint seed = initSeed(uvec2(gl_FragCoord.xy * resolutionFactor), frameCount);
    vec2 pos = ratio(vClipPos.xy) * resolutionFactor + ratio(vec2(1)) * (resolutionFactor - 1);
    vec2 offset = resolutionFactor * vec2(rand(seed), rand(seed)) / winSize;
    vec2 uv = (vClipPos.xy + vec2(1)) * 0.5;

    Ray ray = Ray(
        camera.pos, 
        camera.lookDir, 
        vec3(1),
        vec3(0)
    );
    ray = fovRay(pos, ray);

    Mat planeMat = Mat(MAT_GLOSSY, vec3(0.85), mData(0,0.4));
    Mat sphereMat = Mat(MAT_DIFF, vec3(1, 0, 0), mData0(ballRoughness));
    Mat glassMat = Mat(MAT_GLASS, vec3(1, 0.85, 0.85), mData0(refractionIndex));

    float metallic = metalProperties.w;
    vec3 metalColor = metalProperties.rgb;
    Mat metalMat1 = Mat(MAT_GLOSSY, metalColor, mData(0 / 8.0, metallic));
    Mat metalMat2 = Mat(MAT_GLOSSY, metalColor, mData(2 / 8.0, metallic));
    Mat metalMat3 = Mat(MAT_GLOSSY, metalColor, mData(4 / 8.0, metallic));
    Mat metalMat4 = Mat(MAT_GLOSSY, metalColor, mData(6 / 8.0, metallic));

    Mat sphereMat1 = Mat(MAT_GLASS, metalColor, mData0(1.05));
    Mat sphereMat2 = Mat(MAT_GLASS, metalColor, mData0(1.5));
    Mat sphereMat3 = Mat(MAT_GLASS, metalColor, mData0(4));

    Sphere spheres[NUM_SPHERE];
    spheres[0] = Sphere(vec3(3,-3,-4), 1, sphereMat1);
    /*spheres[1] = Sphere(vec3(0,1,-4), 1, sphereMat2);
    spheres[2] = Sphere(vec3(-3,1, -4), 1, sphereMat3);
    spheres[3] = Sphere(vec3(10, EPS, -5), 2, metalMat3);
    spheres[4] = Sphere(vec3(16, EPS, -5), 2, metalMat4);
    spheres[5] = Sphere(vec3(-6, EPS, -5), 2, glassMat);*/
    
    Plane planes[NUM_PLANE];
    planes[0] = Plane(vec3(0,0,-5), vec3(0,1,0), planeMat);

#if NUM_LIGHT > 0
    Light lights[NUM_LIGHT];
    lights[0] = Light(modelPos, 1.5, vec3(1), 10);
    //lights[1] = Light(vec3(6,5,10), 1.5, vec3(1), 10);
    World world = World(spheres, planes, lights);
#else
    World world = World(spheres, planes);
#endif

    vec4 radiance;
    for(int i = 0; i < samples; i++){
        radiance += max(rayColor(world, seed, ray), 0);
    }

    FragColor = radiance + max(frameCount, 0) * texture(screenTex, uv);
    FragColor /= frameCount + samples;
}